export const people = [
  {
    id: 1,
    bg: "#B1DDF1",
    offset: { x: 0, y: 0 },
    coords: [0, 0],
    direction: "",
    button: "",
    location: "Atlanta",
    miles: "10",
    name: "Amanda",
    age: 29,
  },
  {
    id: 2,
    bg: "#9F87AF",
    offset: { x: 0, y: 0 },
    coords: [0, 0],
    direction: "",
    button: "",
    location: "New orleans",
    miles: "20",
    name: "Mary",
    age: 21,
  },
  {
    id: 3,
    bg: "#88527F",
    offset: { x: 0, y: 0 },
    coords: [0, 0],
    direction: "",
    button: "",
    location: "Georgia",
    miles: "30",
    name: "Myarr",
    age: 39,
  },
  {
    id: 4,
    bg: "#614344",
    offset: { x: 0, y: 0 },
    coords: [0, 0],
    direction: "",
    button: "",
    location: "Washington",
    miles: "29",
    name: "Angela",
    age: 40,
  },
  {
    id: 5,
    bg: "#332C23",
    offset: { x: 0, y: 0 },
    coords: [0, 0],
    direction: "",
    button: "",
    location: "New York",
    miles: "17",
    name: "Micheal",
    age: 35,
  },
  // {
  //   id: 6,
  //   bg: "#FC9F5B",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 7,
  //   bg: "#FBD1A2",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 8,
  //   bg: "#ECE4B7",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 9,
  //   bg: "#7DCFB6",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 10,
  //   bg: "#33CA7F",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 11,
  //   bg: "#8f3333",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 12,
  //   bg: "#6b0a63",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
  // {
  //   id: 13,
  //   bg: "#8de30d",
  //   offset: { x: 0, y: 0 },
  //   coords: [0, 0],
  //   direction: "",
  // button: "",
  // },
];
